version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - paramt
  ignore:
  - dependency-name: youtube-transcript-api
    versions:
    - 0.4.0
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
