language: python
sudo: required
dist: xenial

python:
    - 3.7
    - 3.6

install:
    - pip install matplotlib
    - python setup.py install

script:
    - videocloud https://www.youtube.com/watch?v=MHTizZ_XcUM
